FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# (1a) Add Machine endpoints API 

The API must be able to add newly installed or back-in-service weather machine’s info 
from a mobile app authorized for access by astronauts only  

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {  
            "Id":3,
            "coord":{  
              "lat":145.77,
              "lon":16.92
            },
           
           "MachineInfo":{  
              "DateDeployed":"2017-04-25, 14:00:59",
              "MachineCode":"Extraordinary"
            }
        }


    + Headers (actual but need help what it looks like)
    
    
            
    + Body (actual)      
            [
            
            {  
                "MachineId":3,
                 "coord":{  
                    "lat":145.77,
                    "lon":16.92
                },
               "MachineInfo":{  
                  "DateDeployed":"2017-04-25, 14:00:59",
                  "MachineCode":"Extraordinary"
                }
            }

            ]
            
            
    + Response 201 (application/json) - sample

    + Headers (sample)

            Location: /questions/2

    + Body (sample)

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }